/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import static br.ulbra.view.guruOnline.gerarCor;
import java.util.Calendar;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author morce
 */
public class guruOnline extends javax.swing.JFrame {

    /**
     * Creates new form guruOnline
     */
    public guruOnline() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        gbSexo = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        javax.swing.ButtonGroup buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        edNome = new javax.swing.JTextField();
        lbSexo = new javax.swing.JLabel();
        rbFem = new javax.swing.JRadioButton();
        rbMasc = new javax.swing.JRadioButton();
        lbDia = new javax.swing.JLabel();
        lbMes = new javax.swing.JLabel();
        lbAno = new javax.swing.JLabel();
        cbDia = new javax.swing.JComboBox<>();
        cbMes = new javax.swing.JComboBox<>();
        btConsultar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        lbResultado = new javax.swing.JLabel();
        lbRes1 = new javax.swing.JLabel();
        lbRes2 = new javax.swing.JLabel();
        lbRes3 = new javax.swing.JLabel();
        lbRes4 = new javax.swing.JLabel();
        cbAno = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCheckBox1.setText("jCheckBox1");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jLabel4.setText("jLabel4");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(51, 0, 102));
        lbTitulo.setText("GURU ON-LINE:");
        jPanel1.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        lbNome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbNome.setForeground(new java.awt.Color(51, 0, 102));
        lbNome.setText("NOME:");
        jPanel1.add(lbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 120, 31));
        jPanel1.add(edNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 380, 32));

        lbSexo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbSexo.setForeground(new java.awt.Color(51, 0, 102));
        lbSexo.setText("SEXO:");
        jPanel1.add(lbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 100, 30));

        buttonGroup1.add(rbFem);
        rbFem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rbFem.setForeground(new java.awt.Color(51, 0, 102));
        rbFem.setText("FEMININO");
        rbFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemActionPerformed(evt);
            }
        });
        jPanel1.add(rbFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 130, 34));

        buttonGroup1.add(rbMasc);
        rbMasc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rbMasc.setForeground(new java.awt.Color(51, 0, 102));
        rbMasc.setText("MASCULINO");
        jPanel1.add(rbMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 150, 34));

        lbDia.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbDia.setForeground(new java.awt.Color(51, 0, 102));
        lbDia.setText("DIA");
        jPanel1.add(lbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        lbMes.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbMes.setForeground(new java.awt.Color(51, 0, 102));
        lbMes.setText("MÊS");
        jPanel1.add(lbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        lbAno.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbAno.setForeground(new java.awt.Color(51, 0, 102));
        lbAno.setText("ANO");
        jPanel1.add(lbAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        cbDia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(cbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 110, 40));

        cbMes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro" }));
        cbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesActionPerformed(evt);
            }
        });
        jPanel1.add(cbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 120, 40));

        btConsultar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btConsultar.setForeground(new java.awt.Color(51, 0, 102));
        btConsultar.setText("CONSULTAR");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 190, 40));

        btLimpar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(51, 0, 102));
        btLimpar.setText("LIMPAR");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 140, 40));

        lbResultado.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbResultado.setForeground(new java.awt.Color(51, 0, 102));
        lbResultado.setText("RESULTADO:");
        jPanel1.add(lbResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 310, -1));

        lbRes1.setBackground(new java.awt.Color(102, 255, 51));
        lbRes1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(lbRes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 590, 45));

        lbRes2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(lbRes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 640, 42));

        lbRes3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(lbRes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 620, 50));

        lbRes4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(lbRes4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 690, 600, 50));
        jPanel1.add(cbAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public String gerarSigno(int dia, int mes) {
        String signo;
        signo = "";
        if (dia >= 21 && dia <= 31 && mes == 3 || dia >= 01 && dia <= 20 && mes == 4) {
            signo = "Áries";
        } else if (dia >= 21 && dia <= 30 && mes == 4
                || dia >= 1 && dia <= 20 && mes == 5) {
            signo = "Touro";
        } else if (dia >= 21 && dia <= 31 && mes == 5
                || dia >= 1 && dia <= 20 && mes == 6) {
            signo = "Gemeos";
        } else if (dia >= 21 && dia <= 30 && mes == 6
                || dia >= 1 && dia <= 21 && mes == 7) {
            signo = "Cancer";
        } else if (dia >= 22 && dia <= 31 && mes == 7
                || dia >= 1 && dia <= 22 && mes == 8) {
            signo = "Leão";
        } else if (dia >= 23 && dia <= 31 && mes == 8
                || dia >= 1 && dia <= 22 && mes == 9) {
            signo = "Virgem";
        } else if (dia >= 22 && dia <= 30 && mes == 9
                || dia >= 1 && dia <= 22 && mes == 10) {
            signo = "Libra";
        } else if (dia >= 23 && dia <= 31 && mes == 10
                || dia >= 1 && dia <= 21 && mes == 11) {
            signo = "Escorpião";
        } else if (dia >= 22 && dia <= 30 && mes == 11
                || dia >= 1 && dia <= 21 && mes == 12) {
            signo = "Sagitário";
        } else if (dia >= 22 && dia <= 31 && mes == 12
                || dia >= 1 && dia <= 20 && mes == 1) {
            signo = "Capricórnio";
        } else if (dia >= 21 && dia <= 30 && mes == 1
                || dia >= 1 && dia <= 19 && mes == 2) {
            signo = "Aquário";
        } else if (dia >= 20 && dia <= 28 && mes == 2
                || dia >= 1 && dia <= 20 && mes == 3) {
            signo = "Peixes";
        } else {
            signo = "o dia selecionado para o mes não existe";
        }
        return signo;

    }


    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        String nome, tratamento;
        int dia, mes, ano;
        nome = edNome.getText();

        dia = cbDia.getSelectedIndex();
        mes = cbMes.getSelectedIndex();
        ano = Integer.parseInt(cbAno.getText());
        Calendar hoje = Calendar.getInstance();
        int diaA, mesA, anoA , idade, anoP = 1900;
        diaA = hoje.get(Calendar.DATE);
        mesA = hoje.get(Calendar.MONTH) + 1;
        
        
        anoA = hoje.get(Calendar.YEAR);
        idade = ((anoA * 365 + mesA * 12 + diaA) - (ano * 365 + mes * 12 + dia)) / 365;
        Calendar birthdate = Calendar.getInstance();
        birthdate.set(ano, mes - 1, dia);
       
        
       // JOptionPane.showMessageDialog(null, dia + "/" + mes + "/" + ano);

        if (rbFem.isSelected()) {
            tratamento = "Sra.";
        } else {
            tratamento = "Sr.";
        }

        lbRes1.setText("Bom dia, " + tratamento + " " + nome + " voce é do signo de " + gerarSigno(dia, mes));
        lbRes2.setText("idade:" + idade);
        lbRes3.setText("Numero da sorte: " + gerarSorte());
        lbRes4.setText("Cor da sorte: " + gerarCor());
        
    
    
    

}

    public static int gerarSorte() {

       Random r = new Random();
        int sorte = r.nextInt(99);
        return sorte;

    }//GEN-LAST:event_btConsultarActionPerformed
    public static String gerarCor() {
        String cor[] = {"azul", "rosa", "verde", "amarelo", "cinza", "branco", "preto", "lilas", "vermelho"};
        Random r = new Random();
        int numero = r.nextInt(9);
        return cor[numero];

    }

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        edNome.setText(null);
        cbDia.setSelectedItem(null);
        cbMes.setSelectedItem(null);
        cbAno.setText(null);
        lbRes1.setText(null);
        lbRes2.setText(null);
        lbRes3.setText(null);
        lbRes4.setText(null);
        
    }//GEN-LAST:event_btLimparActionPerformed

    private void rbFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFemActionPerformed

    private void cbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guruOnline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guruOnline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guruOnline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guruOnline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guruOnline().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JTextField cbAno;
    private javax.swing.JComboBox<String> cbDia;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JTextField edNome;
    private javax.swing.ButtonGroup gbSexo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbAno;
    private javax.swing.JLabel lbDia;
    private javax.swing.JLabel lbMes;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbRes1;
    private javax.swing.JLabel lbRes2;
    private javax.swing.JLabel lbRes3;
    private javax.swing.JLabel lbRes4;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JRadioButton rbFem;
    private javax.swing.JRadioButton rbMasc;
    // End of variables declaration//GEN-END:variables
}
